name: 'Clean up unused labels'
description: 'Clean up unused labels from repository'
inputs:
  token:
    description: 'github token, usually "${{ secrets.GITHUB_TOKEN }}"'
    required: true
  exclusions:
    description: 'Which labels to exclude (comma separated)'
    required: false
  filter-regexp:
    description: 'Which labels to include (regexp)'
    required: false
runs:
  using: 'node16'
  main: 'index.js'